### ISSUE TITLE
ВАЖНО

### ISSUE THREAD

**Issue by MaximTkachev** [Chantreck/MAD-SuperDuperQuiz#3]
Пожалуйста, отстаньте от бедного бекендера, он уже устал и хочет **спать**...

**Comment by Chantreck** [comment]
Нет.

**Comment by MaximTkachev** [comment]
грустно...

**Comment by MaximTkachev** [comment]
@Chantreck зачем нам вк, если можно общаться в гите?

**Comment by Chantreck** [comment]
> @Chantreck зачем нам вк, если можно общаться в гите? 

тут даже реакции есть, не то что в вк

**Comment by macoolri** [comment]
всем привет в этом чатике
